#set_property PACKAGE_PIN U13 [get_ports {anodes[0]}]
#set_property PACKAGE_PIN K2  [get_ports {anodes[1]}]
#set_property PACKAGE_PIN T14 [get_ports {anodes[2]}]
#set_property PACKAGE_PIN P14 [get_ports {anodes[3]}]
#set_property PACKAGE_PIN J14 [get_ports {anodes[4]}]
#set_property PACKAGE_PIN T9  [get_ports {anodes[5]}]
#set_property PACKAGE_PIN J18 [get_ports {anodes[6]}]
#set_property PACKAGE_PIN J17 [get_ports {anodes[7]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {anodes[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anodes[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anodes[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anodes[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anodes[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anodes[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anodes[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anodes[7]}]


#set_property PACKAGE_PIN T10 [get_ports {cathodes[0]}]
#set_property PACKAGE_PIN R10 [get_ports {cathodes[1]}]
#set_property PACKAGE_PIN K16 [get_ports {cathodes[2]}]
#set_property PACKAGE_PIN K13 [get_ports {cathodes[3]}]
#set_property PACKAGE_PIN P15 [get_ports {cathodes[4]}]
#set_property PACKAGE_PIN T11 [get_ports {cathodes[5]}]
#set_property PACKAGE_PIN L18 [get_ports {cathodes[6]}]
#set_property PACKAGE_PIN H15 [get_ports {cathodes[7]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[7]}]


#set_property PACKAGE_PIN E3 [get_ports {clk}]
#set_property IOSTANDARD LVCMOS33 [get_ports {clk}]